### ISSUE TITLE
Use the job token as the default GITHUB_TOKEN

### ISSUE THREAD

**Issue by nhedger** [nhedger/setup-exoscale#3]
Let's explore the possibility of using the job token (`${{ github.token }}`) as the default value for the `token` input.

```yaml
inputs:
  token:
    description: GitHub Token
    required: true
    default: ${{ github.token }}
```

This would result in one less thing to consider when setting up the action, and we could remove the caveats section from the README.

### To do

- [ ] Add a new `token` input to `action.yaml`
- [ ] Set its default value to `${{ github.token }}`
- [ ] Remove the caveats section from `README.md`
